version: '3.8'

services:
  clickhouse:
    image: clickhouse/clickhouse-server:23.8
    container_name: wifi_clickhouse
    ports:
      - "8123:8123"  # HTTP接口
      - "9000:9000"  # Native接口
    environment:
      CLICKHOUSE_DB: wifi_tracking
      CLICKHOUSE_USER: admin
      CLICKHOUSE_PASSWORD: admin123
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - ./clickhouse/init:/docker-entrypoint-initdb.d
      - ./clickhouse/config:/etc/clickhouse-server/config.d
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    networks:
      - wifi_network

  # 可选：ClickHouse客户端工具
  clickhouse-client:
    image: clickhouse/clickhouse-client:23.8
    container_name: wifi_clickhouse_client
    depends_on:
      - clickhouse
    networks:
      - wifi_network
    profiles:
      - tools

volumes:
  clickhouse_data:
    driver: local

networks:
  wifi_network:
    driver: bridge